package vista;

import javax.swing.JOptionPane;

public class Convertidor extends javax.swing.JFrame {
    ConvertidorTemperatura conversionTem;
    VentanaPrincipal ventanaPrin;
    ConvertidorMonedas conversionMon;
    ConvertidorLongitud conversionLong;
    
    /**
     * Creates new form Convertidor
     */
    public Convertidor() {
        initComponents();
        this.setTitle("CONVERSOR :)");
                
        ventanaPrin = new VentanaPrincipal();
        ventanaPrin.setBounds(408, 0, 564, 317);
        add(ventanaPrin);
        
        conversionTem = new ConvertidorTemperatura();
        conversionTem.setBounds(408, 0, 564, 317);
        add(conversionTem);
        conversionTem.setVisible(false);
        
        conversionMon = new ConvertidorMonedas();
        conversionMon.setBounds(408, 0, 564, 317);
        add(conversionMon);
        conversionMon.setVisible(false);
        
        conversionLong = new ConvertidorLongitud();
        conversionLong.setBounds(408, 0, 564, 317);
        add(conversionLong);
        conversionLong.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        monedas = new javax.swing.JButton();
        temperatura = new javax.swing.JButton();
        medidas = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 65, 98));

        monedas.setBackground(new java.awt.Color(24, 47, 62));
        monedas.setForeground(new java.awt.Color(255, 255, 255));
        monedas.setText("Monedas");
        monedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedasActionPerformed(evt);
            }
        });

        temperatura.setBackground(new java.awt.Color(24, 47, 62));
        temperatura.setForeground(new java.awt.Color(255, 255, 255));
        temperatura.setText("Temperatura");
        temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperaturaActionPerformed(evt);
            }
        });

        medidas.setBackground(new java.awt.Color(24, 47, 62));
        medidas.setForeground(new java.awt.Color(255, 255, 255));
        medidas.setText("Medidas de Longitud");
        medidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medidasActionPerformed(evt);
            }
        });

        salir.setBackground(new java.awt.Color(24, 47, 62));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setText("Seleccione el tipo de conversion que desea ejecutar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medidas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(monedas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(texto)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(texto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(monedas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(medidas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 564, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedasActionPerformed
        conversionTem.setVisible(false);
        ventanaPrin.setVisible(false);
        conversionMon.setVisible(true);
    }//GEN-LAST:event_monedasActionPerformed

    private void medidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidasActionPerformed
        conversionTem.setVisible(false);
        ventanaPrin.setVisible(false);
        conversionMon.setVisible(false);
        conversionLong.setVisible(true);
    }//GEN-LAST:event_medidasActionPerformed

    private void temperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturaActionPerformed
        conversionTem.setVisible(true);
        ventanaPrin.setVisible(false);
    }//GEN-LAST:event_temperaturaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea Continuar?");
       if(respuesta == JOptionPane.NO_OPTION){
           JOptionPane.showMessageDialog(null, "Programa Finalizado!");
           System.exit(0);
       }else if (respuesta == JOptionPane.CANCEL_OPTION){
           JOptionPane.showMessageDialog(null, "Programa Finalizado!");
           System.exit(0);
       }
       
        
    }//GEN-LAST:event_salirActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new Convertidor().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton medidas;
    private javax.swing.JButton monedas;
    private javax.swing.JButton salir;
    private javax.swing.JButton temperatura;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
