
package vista;

import calculos.OperacionesTemperatura;
import javax.swing.JOptionPane;

public class ConvertidorTemperatura extends javax.swing.JPanel {

    /**
     * Creates new form ConvertidorTemperatura1
     */
    public ConvertidorTemperatura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloT = new javax.swing.JLabel();
        jLabelValor1 = new javax.swing.JLabel();
        valorAConvertir = new javax.swing.JTextField();
        convertirDe = new javax.swing.JComboBox<>();
        convertirA = new javax.swing.JComboBox<>();
        jLabelValor2 = new javax.swing.JLabel();
        valorConvertido = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();

        setBackground(new java.awt.Color(29, 61, 105));

        tituloT.setBackground(new java.awt.Color(29, 61, 105));
        tituloT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloT.setForeground(new java.awt.Color(255, 255, 255));
        tituloT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloT.setText("Convertidor De Temperatura");
        tituloT.setOpaque(true);

        jLabelValor1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelValor1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor1.setText("Ingrese el valor a convertir");

        valorAConvertir.setBackground(new java.awt.Color(255, 255, 255));
        valorAConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorAConvertirActionPerformed(evt);
            }
        });
        valorAConvertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valorAConvertirKeyTyped(evt);
            }
        });

        convertirDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        convertirDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirDeActionPerformed(evt);
            }
        });

        convertirA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit ", "Kelvin" }));
        convertirA.setSelectedIndex(1);

        jLabelValor2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelValor2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor2.setText("Valor convertido");

        valorConvertido.setEditable(false);
        valorConvertido.setBackground(new java.awt.Color(255, 255, 255));

        btnConvertir.setBackground(new java.awt.Color(0, 51, 102));
        btnConvertir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });
        btnConvertir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnConvertirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValor2)
                    .addComponent(jLabelValor1)
                    .addComponent(tituloT)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorAConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(valorConvertido))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convertirA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(convertirDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tituloT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelValor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertirDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelValor2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertirA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConvertir)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void valorAConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorAConvertirActionPerformed
        
    }//GEN-LAST:event_valorAConvertirActionPerformed

    private void convertirDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convertirDeActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        
        if (valorAConvertir.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "No se pueden dejar campos vacios. Por Favor ingresar datos");
        } else {
            try {
                OperacionesTemperatura operacion = new OperacionesTemperatura();
                operacion.conversionLongitud(String.valueOf(valorAConvertir.getText()));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Solo se permiten caracteres numericos", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
            }
        }
       
        
        OperacionesTemperatura operacionLog = new OperacionesTemperatura();
        operacionLog.setLogInicial(convertirDe.getSelectedIndex());
        operacionLog.setLogFinal(convertirA.getSelectedIndex());
        
        valorConvertido.setText(String.valueOf(String.format("%.3f", operacionLog.conversionLongitud(String.valueOf(valorAConvertir.getText())))));
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void valorAConvertirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valorAConvertirKeyTyped

    }//GEN-LAST:event_valorAConvertirKeyTyped

    private void btnConvertirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnConvertirKeyTyped
        
    }//GEN-LAST:event_btnConvertirKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> convertirA;
    private javax.swing.JComboBox<String> convertirDe;
    private javax.swing.JLabel jLabelValor1;
    private javax.swing.JLabel jLabelValor2;
    private javax.swing.JLabel tituloT;
    private javax.swing.JTextField valorAConvertir;
    private javax.swing.JTextField valorConvertido;
    // End of variables declaration//GEN-END:variables
}
