package vista;

import calculos.OperacionesLongitud;
import javax.swing.JOptionPane;

public class ConvertidorLongitud extends javax.swing.JPanel {

    /**
     * Creates new form ConvertidorLongitud
     */
    public ConvertidorLongitud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloT = new javax.swing.JLabel();
        jLabelValor1 = new javax.swing.JLabel();
        valorAConvertir = new javax.swing.JTextField();
        jLabelValor2 = new javax.swing.JLabel();
        valorConvertido = new javax.swing.JTextField();
        btnConvertir = new javax.swing.JButton();
        jBoxConvertirDe = new javax.swing.JComboBox<>();
        jBoxConvertirA = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(29, 61, 105));

        tituloT.setBackground(new java.awt.Color(29, 61, 105));
        tituloT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tituloT.setForeground(new java.awt.Color(255, 255, 255));
        tituloT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloT.setText("Convertidor De Longitud");
        tituloT.setOpaque(true);

        jLabelValor1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelValor1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor1.setText("Ingrese el valor a convertir");

        valorAConvertir.setBackground(new java.awt.Color(255, 255, 255));
        valorAConvertir.setToolTipText("");

        jLabelValor2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabelValor2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelValor2.setText("Valor convertido");

        valorConvertido.setEditable(false);
        valorConvertido.setBackground(new java.awt.Color(255, 255, 255));

        btnConvertir.setBackground(new java.awt.Color(0, 51, 102));
        btnConvertir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        btnConvertir.setText("Convertir");
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        jBoxConvertirDe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kilometros ", "metros", "centimetros", "milimetros", "pulgadas" }));

        jBoxConvertirA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kilometros ", "metros", "centimetros", "milimetros", "pulgadas" }));
        jBoxConvertirA.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valorConvertido)
                            .addComponent(jLabelValor2)
                            .addComponent(valorAConvertir, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(jLabelValor1)
                            .addComponent(tituloT))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBoxConvertirDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBoxConvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(tituloT, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelValor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorAConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxConvertirDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelValor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valorConvertido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBoxConvertirA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnConvertir)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        if (valorAConvertir.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "No se pueden dejar campos vacios. Por Favor ingresar datos");
        } else {
            try {
                OperacionesLongitud operacion = new OperacionesLongitud();
                operacion.conversionLongitud(String.valueOf(valorAConvertir.getText()));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Solo se permiten caracteres numericos", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        OperacionesLongitud operacionLog = new OperacionesLongitud();
        operacionLog.setLogInicial(jBoxConvertirDe.getSelectedIndex());
        operacionLog.setLogFinal(jBoxConvertirA.getSelectedIndex());
        
        valorConvertido.setText(String.valueOf(String.format("%.3f", operacionLog.conversionLongitud(String.valueOf(valorAConvertir.getText())))));
    }//GEN-LAST:event_btnConvertirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JComboBox<String> jBoxConvertirA;
    private javax.swing.JComboBox<String> jBoxConvertirDe;
    private javax.swing.JLabel jLabelValor1;
    private javax.swing.JLabel jLabelValor2;
    private javax.swing.JLabel tituloT;
    private javax.swing.JTextField valorAConvertir;
    private javax.swing.JTextField valorConvertido;
    // End of variables declaration//GEN-END:variables
}
